### ISSUE TITLE
可以生成代码提示文件吗？

### ISSUE THREAD

**Issue by ikilobyte** [jmjoy/phper#36]
扩展里面有哪些函数、类、参数是哪些都没有相关的提示，很不方便编码，希望可以生成Stub文件

**Comment by ikilobyte** [comment]
在macos上，我编译后`examples/hello`是可以运行，那`README`那块是不是要勾选上呀？还是有其他的问题吗？

**Comment by jmjoy** [comment]
> 扩展里面有哪些函数、类、参数是哪些都没有相关的提示，很不方便编码，希望可以生成Stub文件

没整明白是啥需求。

**Comment by jmjoy** [comment]
> 在macos上，我编译后`examples/hello`是可以运行，那`README`那块是不是要勾选上呀？还是有其他的问题吗？

CI里面没有加macos-latest，加了也应该跑不过，你可是试试。

**Comment by erasin** [comment]
没有自动生成， 可以参照 https://github.com/phalcon/ide-stubs , 自己创建 ide-stubs

注意 `composer.json`

https://github.com/phalcon/ide-stubs/blob/e0dcfc28b324ec3fdfd06f1f3a7a34a7411c520d/composer.json#L41-L45

项目引入自己的 ide-stubs 即可有提示了。

**Comment by jmjoy** [comment]
`php --re <extension>`可以获取到扩展的类、方法等信息，至于生成stub，应该有其他方式吧。
